add-friends-likes
SergeiMish/java-filmorate pull request #2
Opened 2024-11-24 08:19 UTC by SergeiMish

2024-11-26 09:51 UTC, NikolaiDem requested changes

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleValidationException(final ValidationException e) {
Все исключения ещё лучше и логировать

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Тип поля должен быть интерфейсом, от реализации не должны зависеть

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Тип поля должен быть интерфейсом, от реализации не должны зависеть

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film postFilm(@RequestBody Film film) {
А валилация?

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exeption/ThrowableException.java
> +public class ThrowableException extends Throwable {
Исключение не информативно

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/interfaces/FilmStorage.java
> +    Film createFilm(Film film);
Film из названий методов можно удалить

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/interfaces/UserStorage.java
> +    User createUser(User user);
User из названий методов можно удалить

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
Лучше ещё добавить методы для добавления и удаления лайков

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
Лучше ещё добавить методы для добавления и удаления друзей

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (limit <= 0) {
Лучше сделать проверку в контроллере

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Типы полей лучше сделать интерфейсами

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Тип поля лучше сделать интерфейсом

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final LocalDate localDateMin = LocalDate.of(1895, 12, 28);
Логика валидации должна быть в контроллере или в сервисе. Репозиторий выполняет только CRUD операции

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getName() == null || film.getName().isEmpty()) {
Валидацию лучше делать через аннотации для уменьшения количества шаблонного кода

2024-11-26 09:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getLogin() == null || user.getLogin().isEmpty()) {
Вся валидация должна быть в контроллере, и выполнять ее лучше ч помощью аннотаций

2024-11-27 15:03 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (limit <= 0) {
Готово

2024-11-27 15:03 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
готово

2024-11-27 15:04 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final LocalDate localDateMin = LocalDate.of(1895, 12, 28);
перенес

2024-11-27 15:06 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getLogin() == null || user.getLogin().isEmpty()) {
Валидацию перенес в контроллер и так же добавил аннотации. Чисто на одних аннотациях тесты не проходят, и либо выводить в отдельный класс каждую, как я это сделал со временем, или оставить как есть. Тесты требуют в ответе определенного кода.

2024-11-27 16:34 UTC, NikolaiDem requested changes

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty()) {
Почему не аннотации?

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(value = "count", defaultValue = "10") int count) {
Можно использовать Positive

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isEmpty()) {
Почему не аннотации?

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film addLike(Long filmId, Long userId) {
Избавиться от дублирования

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Лучше в репозитории создать метод findByIds(...)

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
Это логика сервиса

2024-11-27 16:34 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
Это логика сервиса

2024-11-28 14:33 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film postFilm(@RequestBody Film film) {
готово

2024-11-28 14:33 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty()) {
исправил

2024-11-28 14:33 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(value = "count", defaultValue = "10") int count) {
готово

2024-11-28 14:33 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isEmpty()) {
исправил

2024-11-28 14:33 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/interfaces/FilmStorage.java
> +    Film createFilm(Film film);
готово

2024-11-28 14:34 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/interfaces/UserStorage.java
> +    User createUser(User user);
готово

2024-11-28 14:34 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
готово

2024-11-28 14:34 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film addLike(Long filmId, Long userId) {
готово

2024-11-28 14:34 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
готово

2024-11-28 14:34 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
убрал

2024-11-28 14:34 UTC, SergeiMish commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getName() == null || user.getName().isEmpty()) {
убрал

2024-11-29 11:30 UTC, NikolaiDem approved these changes

2024-11-29 11:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +//        if (film.getName() == null || film.getName().isEmpty()) {
Удалить лишний код

2024-11-29 11:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final ValidateFilm filmValidator;
Можно сделать кастомную валидацию вместо нового сервиса

2024-11-29 11:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getById)
Лучше в репозитории создать метод getByIds(...)

2025-01-03 09:49 UTC, merged